# Generated by Django 4.2.7 on 2025-03-29 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="users",
            field=models.ManyToManyField(
                related_name="company_set",
                through="companies.CompanyUsers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="companyusers",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_users",
                to="companies.company",
            ),
        ),
        migrations.AlterField(
            model_name="companyusers",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_relations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
